version: '3'
services:
  web:
    image: "trainwithshubham/node-app-batch-6:latest"
    image: node:14
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: npm start
